// Generated by CoffeeScript 1.6.3
(function() {
  var trackRobot;

  trackRobot = function(north, east, south, west) {
    return [(north - south) || 0, (east - west) || 0];
  };

  console.log(trackRobot(20, 30, 10, 40));

  console.log([-10, 10]);

  console.log(trackRobot());

  console.log([0, 0]);

  console.log(trackRobot(-10, 20, 10));

  console.log([20, -20]);

  module.exports = {
    trackRobot: trackRobot
  };

}).call(this);
